### ISSUE TITLE
consider rebranding and taking over if official is no longer maintain

### ISSUE THREAD

**Issue by hbt** [hbt/mouseless#48]
wait for official word in https://github.com/1995eaton/chromium-vim/issues/517

**Comment by kalbasit** [comment]
@hbt still waiting for an official word, but I guess we can safely assume that @1995eaton has abandoned the project or have no time to continue maintaining it.

To convince people to switch, we should start by highlighting the major features and fixes applied to the original fork. The [ChangeLog](https://hbt.github.io/mouseless/changelog.html) is very helpful (Thanks!!) but quite noisy to parse.

Also, life changes frequently for everyone, and I am afraid the fate of the original fork is unavoidable. Can we work together to avoid that? Perhaps have it from an organization rather than a personal fork and allocate a team to maintain it? I can contribute up to 5 hours a week max today.

**Comment by hbt** [comment]
## Fork differences:

Feel free to submit a better format for the ChangeLog. 
The documentation began last week-end and it's a work in progress.


## On more users:

Regarding users, my objective is to focus strictly on contributors at this point in time. Having multiple stars on github or multiple users on the google store would only create more work for maintainers (e.g support)
This fork is public mainly to attract more contributions. I've very happy with the progress so far and not planning to advertise aggressively and risk attracting the wrong audience at this stage. 

People who contribute are gonna do it anyway by forking the repo or checking the forks network.


## Long term support:

I'm open to creating an organization but it's too early. If you'd like to contribute, please log an issue, discuss it and send a pull requests. Frequent/trusted contributors will be granted admin rights and we can look into turning the repo into an organization afterwards.

I was a former author on vrome (https://github.com/jinzhu/vrome/blob/master/Thanks.mkd) before, worked on vimum and pentadactyl. 
I do foresee using this extension and maintaining it until something better comes along.

**Comment by Stvad** [comment]
Hey, @hbt I was wondering if you have any updates here. I'd love to see you fork available in Chrome store.

**Comment by hbt** [comment]
End goal has not changed: keep the fork public for contributions, recruit collaborators to share maintenance workload and minimize time/energy on user support.

Hitting the chrome store would only create more user support and isn't worth the time/energy.

**Comment by Stvad** [comment]
Well, you don't have to do the actual user support if you don't want to.
But being on the chrome store will attract more collaborators, make usage of the extension easier for everybody and helps to build the community.

**Comment by hbt** [comment]
then hit the fork button and publish it.
you can pull from me and have a Google store version

**Comment by Stvad** [comment]
I was considering doing that. I'll think about it and notify you If I decide to do so.
